### ISSUE TITLE
v0.6.0

### ISSUE THREAD

**Issue by dpiscia** [bag-cnag/biodm#25]
Hello,

I have run docker compose -f compose.yml up --build -d but once the docker are running I could not access http://localhost:9080/

![Screenshot 2024-09-02 at 15 25 11](https://github.com/user-attachments/assets/5d04ec9a-23a6-419b-8cd6-d1e6239f0476)

**Comment by IvoLeist** [comment]
@Neah-Ko thinking out loud, maybe it would be good to add a healthcheck here:
https://github.com/bag-cnag/biodm/blob/main/compose.yml#L100

so the swagger-ui container run fails when the biodm API is not yet running :thinking:
